version: 2.1

orbs:
  node: circleci/node@5.0

jobs:
  build_deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
          override-ci-command: "yarn install --immutable --mode=skip-build"
      - run:
          name: Deploy to Netlify
          command: |
            npm i --save false --package-lock false @netlify/plugin-nextjs
            yarn netlify deploy --build --prod

workflows:
  deploy_to_netlify:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: main
