version: 2.1

orbs:
  node: circleci/node@5.0

jobs:
  build_deploy_beta:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Deploy to Netlify
          command: |
            [ ! -d node_modules ] && npm i --save false --package-lock false @netlify/plugin-nextjs netlify-cli
            export NETLIFY_SITE_ID="$NETLIFY_SITE_ID_BETA"
            npx netlify deploy --build --prod
      - save_cache:
          name: Caching node_modules
          key: v1-npm-deps-{{ checksum ".circleci/config.yml" }}
          paths:
            - node_modules
workflows:
  deploy_to_netlify_beta:
    jobs:
      - build_deploy_beta:
          filters:
            branches:
              only: canary
