version: 2.1

orbs:
  node: circleci/node@5.0

jobs:
  build_deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - restore_cache:
          keys:
            - v1-npm-deps-{{ checksum ".circleci/config.yml" }}
      - run:
          name: Install Netlify CLI and Plugins
          command: |
            yarn set version classic
            yarn global add @netlify/plugin-nextjs netlify-cli
            yarn set version stable
      - run:
          name: Deploy to Netlify
          command: |
            netlify deploy --build --prod
      - save_cache:
          name: Caching node_modules
          key: v1-npm-deps-{{ checksum ".circleci/config.yml" }}
          paths:
            - ~/.cache/yarn
workflows:
  deploy_to_netlify:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: main
