version: 2.1

orbs:
  node: circleci/node@5.0

jobs:
  build_deploy:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          check-cache: always
          pkg-manager: yarn-berry
          with-cache: false
      - run:
          name: Build the project
          command: yarn build
      - run:
          name: Deploy to Netlify
          command: |
            sudo npm i -g netlify-cli && npx netlify --help
            netlify status

workflows:
  deploy_to_netlify:
    jobs:
      - build_deploy:
          filters:
            branches:
              only: main
