import Head from 'next/head';
import styles from '../styles/Home.module.css';

function Home() {
	return (
		<div>
			<Head>
				<title>Firebase with Next.js</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1>Hello world</h1>
			<div className={styles.card}>
				<h2>Sign In</h2>
				<p>Add your Google account.</p>
			</div>
		</div>
	);
}

export default Home;
